<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\KomponenMesin;
use App\Models\KomponenType;
use App\Models\Mesin;
use App\Models\MesinImage;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);
        $mesin = [
            [
                'kode_mesin' => 'machine001',
                'nama' => 'Cylinder Head',
                'posisi_x' => 120,
                'posisi_y' => 420,
            ],
            [
                'kode_mesin' => 'machine002',
                'nama' => 'Cylinder Block',
                'posisi_x' => 220,
                'posisi_y' => 390,
            ],
            [
                'kode_mesin' => 'machine003',
                'nama' => 'Front Engine Compartment',
                'posisi_x' => 190,
                'posisi_y' => 165,
            ],
            [
                'kode_mesin' => 'machine004',
                'nama' => 'Cooling System',
                'posisi_x' => 420,
                'posisi_y' => 160,
            ],
            [
                'kode_mesin' => 'machine005',
                'nama' => 'Charging System',
                'posisi_x' => 210,
                'posisi_y' => 710,
            ],
            [
                'kode_mesin' => 'machine006',
                'nama' => 'Lubrication System',
                'posisi_x' => 410,
                'posisi_y' => 610,
            ],
            [
                'kode_mesin' => 'machine007',
                'nama' => 'Fuel System',
                'posisi_y' => 720,
                'posisi_x' => 300,
            ],
        ];
        Mesin::insert($mesin);

        $komponenType = [
            [
                'nama' => 'UNIQ',
            ],
            [
                'nama' => 'BULK / LOT',
            ],
        ];
        KomponenType::insert($komponenType);

        $komponen = [
            [
                'id_mesin' => '1',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Kepala Silinder',
                'breakdown_possibility' => '99',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Kepala Silinder png/Kepala-Silinder.png',
                'condition' => rand(0, 100),
                'posisi_x' => 327,
                'posisi_y' => 139,
            ],
            [
                'id_mesin' => '1',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Katup Hisap',
                'breakdown_possibility' => '98',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Kepala Silinder png/Katup-Hisap.png',
                'condition' => rand(0, 100),
                'posisi_x' => 100,
                'posisi_y' => 255,
            ],
            [
                'id_mesin' => '1',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Katup Buang',
                'breakdown_possibility' => '97',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Kepala Silinder png/Katup-Buang.png',
                'condition' => rand(0, 100),
                'posisi_x' => 191,
                'posisi_y' => 111,
            ],
            [
                'id_mesin' => '1',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Poros Nok',
                'breakdown_possibility' => '96',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Kepala Silinder png/Poros-Nok.png',
                'condition' => rand(0, 100),
                'posisi_x' => 167,
                'posisi_y' => 578,
            ],
            [
                'id_mesin' => '1',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Rocker Arm',
                'breakdown_possibility' => '95',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Kepala Silinder png/Rocker-Arm.png',
                'condition' => rand(0, 100),
                'posisi_x' => 360,
                'posisi_y' => 642,
            ],
            [
                'id_mesin' => '1',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Cylinder Head Cover',
                'breakdown_possibility' => '94',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Kepala Silinder png/Cylinder-Head-Cover.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '1',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Busi',
                'breakdown_possibility' => '93',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Kepala Silinder png/Busi-Mobil.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '1',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Intake Manifold',
                'breakdown_possibility' => '92',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Kepala Silinder png/Intake-Manifold.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '1',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Exhaust Manifold',
                'breakdown_possibility' => '91',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Kepala Silinder png/Exhaust-Manifold.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '2',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Blok Silinder',
                'breakdown_possibility' => '99',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Blok Silinder png/Blok-silinder.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '2',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Gasket',
                'breakdown_possibility' => '98',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Blok Silinder png/Gasket.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '2',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Piston',
                'breakdown_possibility' => '97',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Blok Silinder png/Piston-Mobil.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '2',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Ring Piston',
                'breakdown_possibility' => '96',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Blok Silinder png/Ring-Piston.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '2',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Batang Penggerak',
                'breakdown_possibility' => '95',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Blok Silinder png/Batang-Penggerak.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '2',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Poros Engkol',
                'breakdown_possibility' => '94',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Blok Silinder png/Poros-Engkol.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '2',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Carter/Oil Pan',
                'breakdown_possibility' => '93',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Blok Silinder png/Carter-atau-Oil-Pan.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '2',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Drain Plug',
                'breakdown_possibility' => '92',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Blok Silinder png/Drain-Plug.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '2',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Pulley Mesin',
                'breakdown_possibility' => '91',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Blok Silinder png/pulley-demper.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '2',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Flywheel',
                'breakdown_possibility' => '90',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Blok Silinder png/Flywheel.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '3',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Timing Chain Assembly',
                'breakdown_possibility' => '99',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Front Engine png/Timing-Chain-Assembly.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '3',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Timing Chain Cover',
                'breakdown_possibility' => '98',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Front Engine png/Timing-Chain-Cover.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '3',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Motor Starter',
                'breakdown_possibility' => '97',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Front Engine png/Motor-Starter.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '3',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Driver Belt',
                'breakdown_possibility' => '96',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Front Engine png/Driver-Belt.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '3',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Oil Cap',
                'breakdown_possibility' => '95',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Front Engine png/Oil-Cap.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '4',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Radiator',
                'breakdown_possibility' => '99',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pendingin png/Radiator.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '4',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Tutup Radiator',
                'breakdown_possibility' => '98',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pendingin png/Tutup-Radiator.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '4',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Thermostat',
                'breakdown_possibility' => '97',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pendingin png/Thermostat.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '4',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Cooling Fan',
                'breakdown_possibility' => '96',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pendingin png/Cooling-Fan.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '4',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Reservoir Tank (Tangki Cadangan)',
                'breakdown_possibility' => '95',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pendingin png/Reservoir-Tank-Tangki-Cadangan.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '4',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Upper Hose dan Lower Hose',
                'breakdown_possibility' => '94',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pendingin png/Upper-Hose-dan-Lower-Hose.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '4',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Water Temperatur Sensor',
                'breakdown_possibility' => '93',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pendingin png/Water-Temperatur-Sensor.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '4',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Water Jacket',
                'breakdown_possibility' => '92',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pendingin png/Water-Jacket.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '4',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'V-Belt (Sabuk Penggerak)',
                'breakdown_possibility' => '91',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pendingin png/V-belt-Sabuk-Penggerak.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '5',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Alternator',
                'breakdown_possibility' => '99',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pengisian png/Alternator.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '5',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Regulator',
                'breakdown_possibility' => '98',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pengisian png/Regulator.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '5',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Baterai',
                'breakdown_possibility' => '97',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pengisian png/Baterai.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '6',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Pompa Oli (Oil Pump)',
                'breakdown_possibility' => '99',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pelumasan png/Pompa-Oli-Oil-Pump.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '6',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Saringan Oli (Filter Oli)',
                'breakdown_possibility' => '98',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pelumasan png/Saringan-Oli-Filter-Oli.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '6',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Saringan Kasa Oli',
                'breakdown_possibility' => '97',
                'id_type' => rand(1, 2),
                'img' => 'assets/img/mesin/Sistem Pelumasan png/Saringan-Kasa.png',
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
        ];
        KomponenMesin::insert($komponen);

        $komponenMesin2 = [
            [
                'id_mesin' => '7',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Tangki Bahan Bakar (Fuel Tank)',
                'breakdown_possibility' => '99',
                'id_type' => rand(1, 2),
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '7',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Saringan Bahan Bakar (Fuel Filter)',
                'breakdown_possibility' => '98',
                'id_type' => rand(1, 2),
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '7',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Saluran Bahan Bakar',
                'breakdown_possibility' => '97',
                'id_type' => rand(1, 2),
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '7',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Pompa Bahan Bakar',
                'breakdown_possibility' => '96',
                'id_type' => rand(1, 2),
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
            [
                'id_mesin' => '7',
                'kode_komponen' => rand(128047000, 128047359),
                'nama' => 'Karburator',
                'breakdown_possibility' => '95',
                'id_type' => rand(1, 2),
                'condition' => rand(0, 100),
                'posisi_x' => rand(90, 500),
                'posisi_y' => rand(100, 800),
            ],
        ];
        KomponenMesin::insert($komponenMesin2);
    }
}
